apiVersion: v1
kind: Service
metadata:
  name: clusterip
  namespace: final
  labels:
    app: mysql
    owner: Group9
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql