apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    owner: Group9
  name: mysql
  namespace: final
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 372159200162.dkr.ecr.us-east-1.amazonaws.com/db_mysql:latest
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DBPWD
        volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql      
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
      