apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    owner: Group9
  name: mysql
  namespace: group9
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 634809228531.dkr.ecr.us-east-1.amazonaws.com/dbg13:latest
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DBPWD
          